name: Deploy to Dev

on:
  push:
    branches:
      - main

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  build_and_deploy:
    name: Build, Deploy and run Tests
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: install
        run: npm install
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: us-east-1 # use your region here.
      - name: deploy
        run: npm run deploy
      - name: test
        run: SLS_JEST_TAG=dev npm run test
